services:
  - type: web
    name: natures-eye
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: natures-eye-db
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://natures-eye.onrender.com

databases:
  - name: natures-eye-db
    plan: free

